sudo: required

services:
  - docker

before_install:
  - docker pull obolibrary/odkfull

before_script:
  - cd src/ontology

script:
  - ./run.sh make test

# whitelist
branches:
  only:
    - master
    - test-travis

### UNCOMMENT THIS AND ADD YOUR DETAILS:
#notifications:
#  email:
#    - YOURNAME@YOU.ORG
