site_name: Mondo Documentation
docs_dir: docs
site_dir: docs-site
theme:
  name: 'material'
markdown_extensions:
  - toc:
      permalink: True
nav:
    - Introduction: index.md
    - Developer guide
      - Generate token: developer-guide/generate-token.md
      - Release workflow: developer-guide/release.md
      - Repair obsoleted classes: developer-guide/repair-obsoleted-classes.md
      - Set up docker: developer-guide/set-up-docker.md
    - Editor guide
      - Protege set up: editors-guide/a-protege-setup.md
      - GitHub access: editors-guide/b-github-access.md
      - Make good term request: editors-guide/c-make-good-term-request.md
      - GitHub PR workflow: editors-guide/d-github-pr-workflow.md
      - GitHub conflicts: editors-guide/dd-github-conflicts.md
      - Entities: editors-guide/f-entities.md
      - Revise Terms in Mondo: editors-guide/revise-terms-in-mondo.md
      - Logical axioms: editors-guide/g-logical-axioms.md
      - Difs: editors-guide/diffs.md
      - Generate reports: editors-guide/generate-report.md
      - Import terms for logical axioms: editors-guide/import-terms-for-logical-axioms.md
      - Imports: editors-guide/imports.md
      - Merging and obsoleting: editors-guide/merging-and-obsoleting.md
      - Edit website: editors-guide/mondo-website-editing.md
      - Check for and Merge Duplicate annotations in Mondo: editors-guide/NORM.md
      - OMIM slurp: editors-guide/omim-slurp.md
      - Pre-release checklist: editors-guide/pre-release-checklist.md
      - Qualtiy control tests: editors-guide/quality-control-tests.md
      - Quality control: editors-guide/quality-control.md
      - Bulk Editing Using Regular Expressions: editors-guide/regex.md
      - Risky obsoletion check: editors-guide/risky_obsoletion_check.md
      - Merging a ROBOT template into Mondo: editors-guide/robot-template.md
      - Set up new computer: editors-guide/set-up-new-computer.md
      - SOP Splitting Terms: editors-guide/sop_splitting-terms.md
      - Splitting classes: editors-guide/splitting-classes.md
      - Troubleshooting: editors-guide/troubleshooting.md
      - Update external sources: editors-guide/update-external-sources.md
    - Design patterns
      - Design patterns: editors-guide/e-design-patterns.md
      - Patterns: editors-guide/patterns/
