site_name: Mondo Documentation
docs_dir: docs
site_dir: docs-site
theme:
  name: 'material'
markdown_extensions:
  - toc:
      permalink: True
nav:
    - Generate token: generate-token.md
    - Release workflow: release.md
    - Repair obsoleted classes: repair-obsoleted-classes.md
    - Set up docker: set-up-docker.md
    - Introduction: index.md
    - Protege set up: a-protege-setup.md
    - GitHub access: b-github-access.md
    - Make good term request: c-make-good-term-request.md
    - GitHub PR workflow: d-github-pr-workflow.md
    - GitHub conflicts: dd-github-conflicts.md
    - Design patterns: e-design-patterns.md
    - Entities: f-entities.md
    - Revise Terms in Mondo: revise-terms-in-mondo.md
    - Logical axioms: g-logical-axioms.md
    - Difs: diffs.md
    - Generate reports: generate-report.md
    - Import terms for logical axioms: import-terms-for-logical-axioms.md
    - Imports: imports.md
    - Merging and obsoleting: merging-and-obsoleting.md
    - Edit website: mondo-website-editing.md
    - Check for and Merge Duplicate annotations in Mondo: NORM.md
    - OMIM slurp: omim-slurp.md
    - Pre-release checklist: pre-release-checklist.md
    - Qualtiy control tests: quality-control-tests.md
    - Quality control: quality-control.md
    - Bulk Editing Using Regular Expressions: regex.md
    - Risky obsoletion check: risky_obsoletion_check.md
    - Merging a ROBOT template into Mondo: robot-template.md
    - Set up new computer: set-up-new-computer.md
    - SOP Splitting Terms: sop_splitting-terms.md
    - Splitting classes: splitting-classes.md
    - Troubleshooting: troubleshooting.md
    - Update external sources: update-external-sources.md
